server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:8888"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://notification-db:5432/notification_db
    username: notification_user
    password: ${NOTIFICATION_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always