server:
  port: 8080

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 20MB
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
